### ISSUE TITLE
Feature request: Server sync support for new configs

### ISSUE THREAD

**Issue by probablykory** [karkkant/valheim-spearfishing#10]
First off: this is one of my favorite mods, hands down.  A+

Thanks for adding the new config options.  But I'm gonna request that you add serversync support, so that when a setting is changed, the change is enforced across all players.  It's probably not game-breaking, having some players running around with things configured one way, and others another, but I imagine server admins will appreciate it.

Cheers!

**Comment by karkkant** [comment]
Thank you, I'm glad you enjoy it. 😃 

And you are right, it needs serversync. It's next thing to do when I have spare time.

**Comment by karkkant** [comment]
ServerSync is added to v1.0.4. and it's pushed to Thunderstore. Hopefully it works as expected. 😄
