### ISSUE TITLE
A little adjustment idea

### ISSUE THREAD

**Issue by BlackDogTM** [karkkant/valheim-spearfishing#2]
Hi there,

first of all thank you so much for this mod. It's been a really great tweak for the game. 

I've been searching for a while for a mod that makes it customizable what bosses can be hooked by a harpoon. Since the game removed boss mobs from the harpoonable mob list it's been a pain in die ass to hunt down Serpent bosses as bounty and get their item drops. (Epic Loot Bounty Mod). Would it be possible for you to make it customizable what mob (even if it's a boss mob) can be harpooned? 

It doesn't have to be complicated, I just want all the sea serpents, no matter if they are classified as a boss mob or a normal mob to be harpoonable.

Thank you a lot in advance!

**Comment by karkkant** [comment]
Hello, glad that you like the mod.

I aimed this mod to be just an extension to fishing and make it available for early game. It doesn't really change how harpoons work. The customization that you want would require patching completely different thing and it doesn't really fall into this mod's scope. 

If you want to make a separate mod for it, patching/overriding `SE_Harpooned.SetAttacker` method should do the trick.
