### ISSUE TITLE
request: harpoon config or compat

### ISSUE THREAD

**Issue by BETLOG** [karkkant/valheim-spearfishing#9]
Im not sure if i should be requesting:
a) make spearfishing compatible with 	[shudnal-HarpoonExtended-1.1.11](https://thunderstore.io/c/valheim/p/shudnal/HarpoonExtended/)
or
b) add configuration to exclude all harpoons from spearfishing functions.

Which ever is easier I guess.

[edit] the problem is that if i harpoon a fish it just dies, but isnt harpooned so i cannot reel it in.

PS: a pre-bogwitch compatible version is what I'm interested in. At least until I know all of my mods have updated and work.

**Comment by shudnal** [comment]
It would be easy to implement just changing condition
`__instance.m_statusEffectHash == _SE_harpooned_hash` to something like `__instance.m_statusEffectHash == _SE_harpooned_hash || __instance.name.StartsWith("projectile_chitinharpoon")`

**Comment by karkkant** [comment]
I just tested these two mods together and didn't notice any compatibility issues.

About your problem though, did you by any chance have your inventory full when you tried harpooning? This mod doesn't have any "reeling in" feature, it just tries to pickup the fish when it's harpooned. Just noticed an oversight that if the fish cannot be picked up (=inventory is full), it kills the fish same as with bow so you have to go and swim it out of water. This way it also wrongly displays the "harpooned .."-message even though it failed.

**Comment by shudnal** [comment]
The issue is harpooning with HarpoonsExtended allows you to reel fish. And your mod is just destroying it.
HarpoonsExtended clears m_statusEffectHash value of projectile so the condition doesn't work. 

If you change condition
`__instance.m_statusEffectHash == _SE_harpooned_hash` -> `__instance.m_statusEffectHash == _SE_harpooned_hash || __instance.name.StartsWith("projectile_chitinharpoon")` 
it will allow HarpoonExtended to reel fish while bows and spears will still kill and autopickup fish.

**Comment by karkkant** [comment]
That fix isn't very reliable. I'm getting NullReferenceException probably because my hook is called first and the fish is gone before your code runs.

I can look into configurations so you can disable harpoon and/or other projectile categories. There was another request for it as well.

**Comment by karkkant** [comment]
Pushed v1.0.3 to thunderstore. You can disable harpoon fishing and it should fix the issue.

**Comment by shudnal** [comment]
That's nice. Thank you!
It looks like [this issue](https://github.com/karkkant/valheim-spearfishing/issues/5) could also be closed with this changes.

**Comment by BETLOG** [comment]
Most excellent.
Confirming: this works exactly as requested and expected on version `0.218.21 Ashlands (-beta default_prebw )` ie: not the latest, have not tested.
Thank you both very much.
